# Generated by Django 3.0.6 on 2020-05-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
